### PR TITLE
generate scss config and install fourseven:scss package if scss enabl…

### LINKED ISSUE #139: install and configure scss package if option is set
i'm going to submit a PR for this

### PR DESCRIPTION
**Pull request by chrisbutler**
…ed resolves #139 

@cmather @scottmcpherson is this too opinionated?

### CODE REVIEW

**Comment by scottmcpherson** [comment]
@chrisbutler sorry for the late response. I use fourseven:sass for just about all of my projects too. But I think we're leaning towards having pluggable generators and commands and also possibly a customizable global config file. 

The global config file will allow you to define any number of packages that you want to install by default. And the pluggable generators and commands would allow you to create custom generators and possibly override the default commands and generators. 

For now, it might be best to hold off on this. The only concern I have with this approach is hard wiring a particular sass package. That would probably be better to put in a global config file or custom generator.

**Comment by chrisbutler** [comment]
@scottmcpherson if we're merging things like https://github.com/iron-meteor/iron-cli/commit/3b3f3b6b36f3ab33b5b43bbba93d8a5ba3491c0c then i think including this for now makes sense, no?

and in terms of this specific case, scss is arguably a lot less useful without the ability to control file load order, so that you can define variables at the top that can be accessed from all of your stylesheets.

i could also add it as a variant of scss, so both options will be available. but fourseven:scss is the top choice by a drastic margin, and currently we create scss files with no package to support them, meaning an app generated with that configuration is broken by default.

do you have specific changes i could make that would bring this inline with what you're suggesting, or do you think it can be merged based on the above?

**Comment by rpierreye** [comment]
:+1:

**Comment by chrisbutler** [comment]
@scottmcpherson @cmather it seems like this would also partially solve for https://github.com/iron-meteor/iron-cli/issues/72#issuecomment-77911458

**Comment by chrisbutler** [comment]
@scottmcpherson what's the rationale for merging https://github.com/iron-meteor/iron-cli/commit/2b73ec4a72c6050ff29b13b685f7639ab10009f3 but holding off on this?

**Comment by scottmcpherson** [comment]
Sorry @chrisbutler. There was no rational. Just busy with other work. Thanks for staying on top of this :+1:

**Pull request merged**
