### PR TITLE
Fix iron debug command.

### PR DESCRIPTION
**Pull request by josephdburdick**
This PR automatically loads config/development/env.sh and config/development/settings.json files when the user runs `iron debug` and also returns the current version of the CLI.

### CODE REVIEW

**Comment by josephdburdick** [comment]
@cmather Hey Chris, since you haven't merged this PR (I respect whatever reason you have not to do so) and I'd like this to at least work for myself, can you explain to me how I can install my fork so I'm using my version until you address the `iron debug` settings.json bug? Thanks!

**Comment by cmather** [comment]
sorry just haven't had time :(. But will certainly show you how to install your own local version. From inside your project directory you can simply use the `npm link` command to link to your local version. See: https://docs.npmjs.com/cli/link.

**Comment by josephdburdick** [comment]
Awesome, thanks Chris!

**Comment by josephdburdick** [comment]
This works great, thanks again.

**Comment by josephdburdick** [comment]
Just a reminder, iron debug command is currently broken if a user wants to use their settings.json.

**Comment by josephdburdick** [comment]
@scottmcpherson Hey, I don't mean to be a thorn or anything but I use Iron CLI and refer it to my friends. When they see me iron debug and it works but it doesn't for them, it makes this repo look bad. Please let me know what I can do to improve this as this PR has been outstanding for nearly a month.

**Comment by chrisbutler** [comment]
@josephdburdick @cmather @scottmcpherson this looks good to me. any objections to merging?

**Comment by josephdburdick** [comment]
No objections here, thanks!

**Comment by chrisbutler** [comment]
@josephdburdick can you update the PR so it's mergeable?

**Comment by josephdburdick** [comment]
@chrisbutler  that should do it, apologies about the delay.

**Comment by chrisbutler** [comment]
@josephdburdick this looks great, thank you!

**Pull request merged**
