### PR TITLE
Fix self closing meta tag in head.html for jade projects

### PR DESCRIPTION
**Pull request by raduchiriac**

### CODE REVIEW

**Comment by chrisbutler** [comment]
@scottmcpherson this looks right to me... any insight on the original content (with the pipes?)

**Comment by raduchiriac** [comment]
I don't think you need `pipes` on this. It's only used for plain text

**Comment by chrisbutler** [comment]
@raduchiriac that's what i was thinking

**Comment by scottmcpherson** [comment]
Yeah, not too sure about the pipes. I don't use jade, so it's possible I originally referenced it from somewhere else. Looks right to me though.

**Pull request merged**
