### PR TITLE
cleanup, controller updates

### PR DESCRIPTION
**Pull request by chrisbutler**

### CODE REVIEW

**Comment by chrisbutler** [comment]
@cmather @scottmcpherson can you take a look at this?

there are a lot of 'changes' but most of it is removing the 'hardcoded' template files and generating them by invoking the templates. the more i dig into the code the more i realize there's a very solid base here

**Comment by scottmcpherson** [comment]
You can thank Chris for the solid base :)  

I honestly don't have the time right this minute to go through this code thourougly, but just from skimming it looks good. I would just manually run through testing any edge case that you can think before releasing.

**Comment by chrisbutler** [comment]
alright, i think that covers everything. i've tested all the options and everything is working as far as i can tell

**Comment by cmather** [comment]
amazing, thanks for diving in @chrisbutler!

**Pull request merged**
