### PR TITLE
fixed #198&#199 "iron g" bugs on windows

### LINKED ISSUE #198: Windows:iron g:controller todos/show_todo bug
on linux, it comes:
created lib/controllers/todos
created lib/controllers/todos/show_todo_controller.js

BUT,

on windows, it comes:
created app\lib\controllers\todos_show_todo_controller.js

### PR DESCRIPTION
**Pull request by spyhole**
Windows:iron g:route webhooks/stripe --where "server" bug #199
Windows:iron g:controller todos/show_todo bug #198

### CODE REVIEW

**Comment by chrisbutler** [comment]
@spyhole this is awesome!

i haven't looked too closely yet, have you tested these changes to see if they break anything on the OSX/linux side?

**Comment by spyhole** [comment]
osx
ubuntu
win10

all env is base on 64bit, npm v2.11.3/node v0.12.7/meteor v1.1.0.3/iron-meteor v1.3.0(1.3.1)
--------------------------------------------
ubuntu's npm version                                                                                                                                                            
{ npm: '2.11.3',                                                                                                                                                                   
  http_parser: '2.3',                                                                                                                                                              
  modules: '14',                                                                                                                                                                   
  node: '0.12.7',                                                                                                                                                                  
  openssl: '1.0.1p',                                                                                                                                                               
  uv: '1.6.1',                                                                                                                                                                     
  v8: '3.28.71.19',                                                                                                                                                                
  zlib: '1.2.8' }

**Comment by spyhole** [comment]
anybody here? @chrisbutler @scottmcpherson

**Comment by spyhole** [comment]
@chrisbutler , i think you can accept this pull request for windows users.

**Comment by chrisbutler** [comment]
@spyhole merged

**Pull request merged**
